[advisories]
ignore = [
    "RUSTSEC-2021-0139" # ansi_term is unmaintained
]

[licenses]
allow-osi-fsf-free = "neither"
confidence-threshold = 0.8
unlicensed = "deny"
copyleft = "deny"
default = "deny"
allow = [
    "MIT",
    "AGPL-3.0",
    "Apache-2.0",
    "BSD-3-Clause",
    "Unicode-DFS-2016",
]

[sources.allow-org]
github = ["rjzak", "WebAssembly"]
# rjzak: temporary until https://github.com/hyperium/hyper/pull/2900 is merged
# WebAssembly: wasi-crypto-guest isn't published on crates.io
